"""Pydantic v2 schemas for the newsletter endpoints.

Three endpoints, three request shapes:
- POST /api/v1/newsletter/subscribe   (public form)
- GET  /api/v1/newsletter/confirm     (clicked from confirmation email)
- GET  /api/v1/newsletter/unsubscribe (clicked from footer / one-click)

All three are intentionally public (no API key required) — that's the whole
point of a signup flow. We rely on token-based authorization (the
confirm_token is a 32-byte URL-safe secret, generated by subscribe()).
Rate-limiting and bot-detection are out of scope here — put them in front
of /api/v1/newsletter/subscribe via a CDN rule or an upstream gateway.

We deliberately do NOT use pydantic.EmailStr — that pulls in the
`email-validator` package, which isn't in requirements.txt and adds a
~10MB transitive (dnspython, idna) for a single field. A plain `str`
plus a one-line regex is enough; the real validation happens in the
service layer (newsletter_sender.subscribe).
"""
from __future__ import annotations

import re
from typing import Optional

from pydantic import BaseModel, Field, field_validator

# Permissive RFC 5321-ish local-part. We don't enforce RFC 5322 exactly
# because the goal is "looks like an email" not "RFC conformance" —
# newsletter_sender.subscribe does the authoritative check.
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


class SubscribeRequest(BaseModel):
    """Body of POST /api/v1/newsletter/subscribe."""
    email: str = Field(..., min_length=3, max_length=254,
                       description="Subscriber email (validated server-side)")
    source: str = Field(
        "direct",
        description="Where the signup came from — direct, instagram_bio, fanvue, referral, import",
    )
    referrer: Optional[str] = Field(
        None,
        description="Optional attribution handle — IG post id, Fanvue DM id, etc.",
    )
    utm_source: Optional[str] = Field(None, description="UTM source")
    utm_campaign: Optional[str] = Field(None, description="UTM campaign")

    @field_validator("email")
    @classmethod
    def _looks_like_email(cls, v: str) -> str:
        v = v.strip().lower()
        if not _EMAIL_RE.match(v):
            raise ValueError("invalid email format")
        return v

    @field_validator("source")
    @classmethod
    def _valid_source(cls, v: str) -> str:
        # Keep the same allow-list the DB CHECK constraint uses; the API
        # never sends a value the DB would reject.
        allowed = {"direct", "instagram_bio", "fanvue", "referral", "import"}
        if v not in allowed:
            raise ValueError(f"source must be one of {sorted(allowed)}")
        return v


class SubscribeResponse(BaseModel):
    """Always returned (200) for a syntactically valid email, so a probe
    can't enumerate which addresses are already on the list."""
    status: str = Field("ok", description="Always 'ok' on valid input")
    already_subscribed: bool = Field(
        False,
        description="True if the email was already pending or active; the UI should still say 'check your inbox'.",
    )
    confirm_url: Optional[str] = Field(
        None,
        description="Absolute confirm URL the UI can render as a 'click here if you don't get the email' fallback. Only present in dev.",
    )


class GenericActionResponse(BaseModel):
    """Returned by /confirm and /unsubscribe — both are simple acknowledgements.
    The UI can render an HTML page based on `status` ('ok' or 'error')."""
    status: str = Field(..., description="'ok' or 'error'")
    email: Optional[str] = Field(
        None,
        description="The email we acted on (confirm only). Null for unsubscribe to prevent enumeration.",
    )
    message: str = Field("", description="Human-readable summary for the UI")
